import { z } from 'zod';

const statusEnum = z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED']);

export const universitySchema = z.object({
    name: z.string().min(1, 'University name is required.'),
    code: z.string().optional(),
    type: z.enum(['PUBLIC', 'PRIVATE', 'CHARTERED', 'FAITH_BASED', 'OTHER']).default('PUBLIC'),
    established_date: z.string().optional(),
    accreditation_body: z.string().optional(),
    accreditation_status: z.string().optional(),
    accreditation_expiry: z.string().optional(),
    address: z.string().optional(),
    phone: z.string().optional(),
    email: z.string().email('Invalid email format.').optional().or(z.literal('')),
    website: z.string().url('Website must start with http:// or https://.').optional().or(z.literal('')),
    timezone: z.string().optional(),
    locale: z.string().optional(),
    currency: z.string().optional(),
    logo_url: z.string().optional(),
    favicon_url: z.string().optional(),
    primary_color: z.string().optional(),
    secondary_color: z.string().optional(),
    contact_person_name: z.string().optional(),
    contact_person_email: z.string().email('Invalid email format.').optional().or(z.literal('')),
    contact_person_phone: z.string().optional(),
    mission_statement: z.string().optional(),
    vision_statement: z.string().optional(),
    motto: z.string().optional(),
    max_campuses: z.string().optional(),
    max_students: z.string().optional(),
    status: statusEnum.default('ACTIVE'),
});

export const editUniversitySchema = universitySchema;

export const emptyUniversityValues = {
    name: '',
    code: '',
    type: 'PUBLIC',
    established_date: '',
    accreditation_body: '',
    accreditation_status: '',
    accreditation_expiry: '',
    address: '',
    phone: '',
    email: '',
    website: '',
    timezone: 'UTC',
    locale: 'en',
    currency: 'USD',
    logo_url: '',
    favicon_url: '',
    primary_color: '',
    secondary_color: '',
    contact_person_name: '',
    contact_person_email: '',
    contact_person_phone: '',
    mission_statement: '',
    vision_statement: '',
    motto: '',
    max_campuses: '',
    max_students: '',
    status: 'ACTIVE',
};
