import { BarChart3, BookOpen, Building2, ClipboardCheck, FileBarChart, GraduationCap, LayoutDashboard, Receipt, Settings, ShieldCheck, UserCog, Users, } from 'lucide-react';
import { ROLES } from '@/lib/roles';
export const navigationItems = [
    {
        title: 'Dashboard',
        href: '/dashboard',
        icon: LayoutDashboard,
        roles: [ROLES.ADMIN, ROLES.REGISTRAR, ROLES.TEACHER, ROLES.ACCOUNTANT, ROLES.STUDENT],
        permissions: ['dashboard:view'],
    },
    {
        title: 'Students',
        href: '/students',
        icon: GraduationCap,
        roles: [ROLES.ADMIN, ROLES.REGISTRAR],
        permissions: ['students:manage'],
    },
    {
        title: 'Teachers',
        href: '/teachers',
        icon: Users,
        roles: [ROLES.ADMIN],
        permissions: ['settings:manage'],
    },
    {
        title: 'Departments',
        href: '/departments',
        icon: Building2,
        roles: [ROLES.ADMIN, ROLES.REGISTRAR],
        permissions: ['students:manage'],
    },
    {
        title: 'Courses',
        href: '/courses',
        icon: BookOpen,
        roles: [ROLES.ADMIN, ROLES.REGISTRAR, ROLES.STUDENT],
        permissions: ['courses:manage', 'courses:view'],
    },
    {
        title: 'Attendance',
        href: '/attendance',
        icon: ClipboardCheck,
        roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
        permissions: ['attendance:manage', 'attendance:view'],
    },
    {
        title: 'Exams',
        href: '/exams',
        icon: FileBarChart,
        roles: [ROLES.ADMIN],
        permissions: ['settings:manage'],
    },
    {
        title: 'Results',
        href: '/results',
        icon: BarChart3,
        roles: [ROLES.ADMIN, ROLES.TEACHER, ROLES.STUDENT],
        permissions: ['results:manage', 'results:view'],
    },
    {
        title: 'Payments',
        href: '/payments',
        icon: Receipt,
        roles: [ROLES.ADMIN, ROLES.ACCOUNTANT, ROLES.STUDENT],
        permissions: ['payments:manage', 'payments:view'],
    },
    {
        title: 'Reports',
        href: '/reports',
        icon: FileBarChart,
        roles: [ROLES.ADMIN],
        permissions: ['settings:manage'],
    },
    {
        title: 'Settings',
        href: '/settings',
        icon: Settings,
        roles: [ROLES.ADMIN],
        permissions: ['settings:manage'],
    },
    {
        title: 'Roles & Permissions',
        href: '/settings/roles',
        icon: ShieldCheck,
        roles: [ROLES.ADMIN],
        permissions: ['settings:manage'],
    },
    {
        title: 'Users',
        href: '/settings/users',
        icon: UserCog,
        roles: [ROLES.ADMIN],
        permissions: ['settings:manage'],
    },
];
