export const ORG_STATUSES = ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED'];
export const COURSE_STATUSES = ['ACTIVE', 'INACTIVE'];
export const INVOICE_STATUSES = ['PAID', 'PENDING', 'PARTIAL', 'OVERDUE', 'CANCELLED'];
export const ATTENDANCE_STATUSES = ['PRESENT', 'ABSENT', 'LATE'];
export const EXAM_STATUSES = ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];
