export const departments = ['Computer Science', 'Business', 'Engineering', 'Health Sciences', 'Education'];
export const programs = [
    'BSc Software Engineering',
    'BBA Accounting',
    'BEng Civil Engineering',
    'BSc Nursing',
    'BA Education',
];
export const studentStatuses = ['Active', 'Pending', 'Graduated', 'Suspended'];
export const genders = ['Female', 'Male', 'Other'];
export const students = [
    {
        id: 'STU-2026-001',
        firstName: 'Amina',
        lastName: 'Hassan',
        gender: 'Female',
        dateOfBirth: '2004-02-18',
        email: 'amina.hassan@ocms.edu',
        phone: '+1 555 0101',
        address: '142 College Avenue, Block B',
        department: 'Computer Science',
        program: 'BSc Software Engineering',
        enrollmentDate: '2026-01-12',
        status: 'Active',
    },
    {
        id: 'STU-2026-002',
        firstName: 'Daniel',
        lastName: 'Okafor',
        gender: 'Male',
        dateOfBirth: '2003-09-24',
        email: 'daniel.okafor@ocms.edu',
        phone: '+1 555 0102',
        address: '88 Union Street',
        department: 'Business',
        program: 'BBA Accounting',
        enrollmentDate: '2026-01-14',
        status: 'Active',
    },
    {
        id: 'STU-2026-003',
        firstName: 'Leila',
        lastName: 'Mohamed',
        gender: 'Female',
        dateOfBirth: '2005-04-11',
        email: 'leila.mohamed@ocms.edu',
        phone: '+1 555 0103',
        address: '19 Library Road',
        department: 'Health Sciences',
        program: 'BSc Nursing',
        enrollmentDate: '2026-02-03',
        status: 'Pending',
    },
    {
        id: 'STU-2026-004',
        firstName: 'Mateo',
        lastName: 'Rivera',
        gender: 'Male',
        dateOfBirth: '2002-12-05',
        email: 'mateo.rivera@ocms.edu',
        phone: '+1 555 0104',
        address: '331 Campus Drive',
        department: 'Engineering',
        program: 'BEng Civil Engineering',
        enrollmentDate: '2025-09-02',
        status: 'Active',
    },
    {
        id: 'STU-2026-005',
        firstName: 'Grace',
        lastName: 'Kimani',
        gender: 'Female',
        dateOfBirth: '2001-07-17',
        email: 'grace.kimani@ocms.edu',
        phone: '+1 555 0105',
        address: '75 North Hall',
        department: 'Education',
        program: 'BA Education',
        enrollmentDate: '2024-08-28',
        status: 'Graduated',
    },
    {
        id: 'STU-2026-006',
        firstName: 'Noah',
        lastName: 'Bennett',
        gender: 'Male',
        dateOfBirth: '2004-06-20',
        email: 'noah.bennett@ocms.edu',
        phone: '+1 555 0106',
        address: '420 Science Lane',
        department: 'Computer Science',
        program: 'BSc Software Engineering',
        enrollmentDate: '2026-03-15',
        status: 'Suspended',
    },
    {
        id: 'STU-2026-007',
        firstName: 'Sara',
        lastName: 'Patel',
        gender: 'Female',
        dateOfBirth: '2003-01-30',
        email: 'sara.patel@ocms.edu',
        phone: '+1 555 0107',
        address: '9 Finance Court',
        department: 'Business',
        program: 'BBA Accounting',
        enrollmentDate: '2025-01-20',
        status: 'Active',
    },
    {
        id: 'STU-2026-008',
        firstName: 'Omar',
        lastName: 'Farah',
        gender: 'Male',
        dateOfBirth: '2002-10-09',
        email: 'omar.farah@ocms.edu',
        phone: '+1 555 0108',
        address: '58 Engineering Way',
        department: 'Engineering',
        program: 'BEng Civil Engineering',
        enrollmentDate: '2024-09-01',
        status: 'Active',
    },
];
export function getStudentFullName(student) {
    return `${student.firstName} ${student.lastName}`;
}
export function getStudentById(id) {
    return students.find((student) => student.id === id);
}
