import { z } from 'zod';

const statusEnum = z.enum(['ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED']);

export const campusSchema = z.object({
    name: z.string().min(1, 'Campus name is required.'),
    code: z.string().min(1, 'Campus code is required.'),
    university_id: z.string().min(1, 'University is required.'),
    address: z.string().optional(),
    phone: z.string().optional(),
    email: z.string().email('Invalid email format.').optional().or(z.literal('')),
    website: z.string().url('Website must start with http:// or https://.').optional().or(z.literal('')),
    established_date: z.string().optional(),
    campus_type: z.string().optional(),
    total_area: z.string().optional(),
    built_up_area: z.string().optional(),
    libraries: z.string().optional(),
    labs: z.string().optional(),
    sports_facilities: z.string().optional(),
    hostels: z.string().optional(),
    auditoriums: z.string().optional(),
    cafeterias: z.string().optional(),
    health_center: z.string().optional(),
    transport_routes: z.string().optional(),
    facilities: z.string().optional(),
    dean_name: z.string().optional(),
    dean_email: z.string().email('Invalid email format.').optional().or(z.literal('')),
    dean_phone: z.string().optional(),
    registrar_name: z.string().optional(),
    registrar_email: z.string().email('Invalid email format.').optional().or(z.literal('')),
    registrar_phone: z.string().optional(),
    description: z.string().optional(),
    vision: z.string().optional(),
    mission: z.string().optional(),
    max_faculties: z.string().optional(),
    max_students: z.string().optional(),
    student_capacity: z.string().optional(),
    status: statusEnum.default('ACTIVE'),
});

export const editCampusSchema = campusSchema;

export const emptyCampusValues = {
    name: '',
    code: '',
    university_id: '',
    address: '',
    phone: '',
    email: '',
    website: '',
    established_date: '',
    campus_type: '',
    total_area: '',
    built_up_area: '',
    libraries: '',
    labs: '',
    sports_facilities: '',
    hostels: '',
    auditoriums: '',
    cafeterias: '',
    health_center: '',
    transport_routes: '',
    facilities: '',
    dean_name: '',
    dean_email: '',
    dean_phone: '',
    registrar_name: '',
    registrar_email: '',
    registrar_phone: '',
    description: '',
    vision: '',
    mission: '',
    max_faculties: '',
    max_students: '',
    student_capacity: '',
    status: 'ACTIVE',
};
